include ../../Makefile.generic

component.cmo : ../events/eventTarget.cmo
control.cmo : component.cmo
button.cmo : control.cmo
popup.cmo : ../positioning/abstractPosition.cmo ../positioning/anchoredPosition.cmo popupBase.cmo